version: "3.8"

services:

  tomcat:
    build:
      context: ./docker/tomcat
    ports:
      - "8081:8080"
    volumes:
      - ./target/docker-task-1.0.war:/usr/local/tomcat/webapps/docker-task-1.0.war
    networks:
      - rabbitmq_tomcat_net

  rabbitmq:
    image: "rabbitmq:3.8.19-management-alpine"
    ports:
      - "8080:8080"
      - "15672:15672"
    volumes:
      - ./docker/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
      - ./docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    hostname: my-rabbit
    networks:
      - rabbitmq_tomcat_net

networks:
  rabbitmq_tomcat_net:
    driver: bridge
