version: "3.8"

services:

  tomcat:
    build:
      context: ./docker/tomcat
    ports:
      - 8081:8080
#    volumes:
#      - ./target/docker-task-1.0.war:/usr/local/tomcat/webapps/docker-task-1.0.war
    networks:
      - rabbitmq_tomcat_net

  rabbitmq:
    build:
      context: ./docker/rabbitmq
    ports:
      - 8080:5672
      - 15672:15672
    networks:
      - rabbitmq_tomcat_net

networks:
  rabbitmq_tomcat_net:
    driver: bridge
