version: "3.8"

services:

  tomcat:
    depends_on:
      - rabbitmq
    build:
      context: ./docker/tomcat
    container_name: Tomcat
    ports:
      - 8081:8080
    networks:
      - rabbitmq_tomcat_net

  rabbitmq:
    build:
      context: ./docker/rabbitmq
    container_name: RabbitMq
    ports:
      - 8080:5672
      - 15672:15672
    networks:
      - rabbitmq_tomcat_net

networks:
  rabbitmq_tomcat_net:
    driver: bridge
